# Generated by Django 4.0.2 on 2022-05-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'single'), ('married', 'married')], max_length=15, null=True)),
            ],
        ),
    ]
