# Generated by Django 4.0.2 on 2022-05-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_jobapplication_eduction_highest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='applications/audio/'),
        ),
    ]
